const ORDER_STATUSES = Object.freeze({
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED"
});

const PURCHASE_LOG_ACTIONS = Object.freeze({
  REQUEST_RECEIVED: "REQUEST_RECEIVED",
  STOCK_READ: "STOCK_READ",
  STOCK_UPDATED: "STOCK_UPDATED",
  ORDER_CREATED: "ORDER_CREATED"
});

const PURCHASE_LOG_RESULTS = Object.freeze({
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED"
});

module.exports = {
  ORDER_STATUSES,
  PURCHASE_LOG_ACTIONS,
  PURCHASE_LOG_RESULTS
};
