const ORDER_STATUSES = Object.freeze({
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED"
});

const ORDER_FAILURE_REASONS = Object.freeze({
  DUPLICATE_REQUEST: "DUPLICATE_REQUEST",
  OUT_OF_STOCK: "OUT_OF_STOCK",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR"
});

const PURCHASE_LOG_ACTIONS = Object.freeze({
  ARTIFICIAL_DELAY_ENDED: "ARTIFICIAL_DELAY_ENDED",
  ARTIFICIAL_DELAY_STARTED: "ARTIFICIAL_DELAY_STARTED",
  PRODUCT_READ: "PRODUCT_READ",
  PURCHASE_NO_LOCK_FAILED: "PURCHASE_NO_LOCK_FAILED",
  PURCHASE_NO_LOCK_STARTED: "PURCHASE_NO_LOCK_STARTED",
  PURCHASE_NO_LOCK_SUCCESS: "PURCHASE_NO_LOCK_SUCCESS",
  PURCHASE_REQUEST_RECEIVED: "PURCHASE_REQUEST_RECEIVED",
  REQUEST_RECEIVED: "REQUEST_RECEIVED",
  STOCK_CHECK_FAILED: "STOCK_CHECK_FAILED",
  STOCK_CHECK_PASSED: "STOCK_CHECK_PASSED",
  STOCK_READ: "STOCK_READ",
  STOCK_UPDATED: "STOCK_UPDATED",
  ORDER_CREATED: "ORDER_CREATED"
});

const PURCHASE_LOG_RESULTS = Object.freeze({
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED"
});

module.exports = {
  ORDER_FAILURE_REASONS,
  ORDER_STATUSES,
  PURCHASE_LOG_ACTIONS,
  PURCHASE_LOG_RESULTS
};
