const HTTP_STATUS = Object.freeze({
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
});

const ERROR_CODES = Object.freeze({
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_TOKEN: "INVALID_TOKEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  FORBIDDEN: "FORBIDDEN",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  CONFLICT: "CONFLICT",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
  DUPLICATE_PRODUCT_CODE: "DUPLICATE_PRODUCT_CODE",
  DUPLICATE_REQUEST: "DUPLICATE_REQUEST",
  LOCK_TIMEOUT: "LOCK_TIMEOUT",
  LOCK_SERVICE_UNAVAILABLE: "LOCK_SERVICE_UNAVAILABLE",
  LOCK_RELEASE_FAILED: "LOCK_RELEASE_FAILED",
  OUT_OF_STOCK: "OUT_OF_STOCK",
  CONFIRMATION_REQUIRED: "CONFIRMATION_REQUIRED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE"
});

const RESPONSE_MESSAGES = Object.freeze({
  SUCCESS: {
    DEFAULT: "Request processed successfully",
    HEALTH_CHECK_OK: "Service is healthy"
  },
  ERROR: {
    DEFAULT: "Request failed",
    INTERNAL_SERVER_ERROR: "Internal server error"
  }
});

const APP_HEADERS = Object.freeze({
  REQUEST_ID: "x-request-id"
});

module.exports = {
  APP_HEADERS,
  ERROR_CODES,
  HTTP_STATUS,
  RESPONSE_MESSAGES
};
